version: "3.9"

services: 
    app: 
        build:
            context: .
            dockerfile: Dockerfile
            args:
              buildno: 1
        ports: 
            - "8000:80"             
    rabbitmq:
        image: "bitnami/rabbitmq:3.7"
        ports: 
        - "4000:4000"
        - "15672:15672"
        volumes:
        - "rabbitmq_data:/bitnami"        
    celery-flower:
        image: gregsi/latest-celery-flower-docker:latest
        ports:
        - "5555:5555" 
        environment:
            - FLOWER_BASIC_AUTH=user:password                      
volumes:
  rabbitmq_data:
    driver: local
# If we are going to use a database in another container
# must be put here as a service